name: beach

channels:
  - conda-forge

dependencies:
  # Core
  - python=3.10
  - numpy=1.23
  - scipy=1.10
  - pandas=1.5
  - xarray=2022.11
  - netcdf4=1.6

  # Visualization
  - matplotlib
  - seaborn=0.12
  - plotly=5.13
  - windrose=1.9
  - panel=1.2

  # Coastal / ocean tools
  - gsw
  - utide=0.3
  - shapely=2.0

  # Utilities
  - sympy=1.12
  - progressbar2

  # Jupyter
  - jupyterlab=3.5
  - notebook=6.5
